# Change these first
owner: john-pope # Your GitHub organization or username, where this repository lives
repo: monocle-status # The name of this repository

sites:
  - name: Monocle
    url: https://monocle.usu.edu/api/health-check
  - name: Monocle PPRD
    url: https://monoclepprd.usu.edu/api/health-check

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /monocle-status
  logoUrl: https://monocle.usu.edu/_next/image?url=%2Fimages%2Fbrand%2Fmonocle-logo.svg&w=64&q=75
  name: Monocle Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /monocle-status
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
